#!wing
#!version=6.0
##################################################################
# Wing IDE project file : User-specific branch                   #
##################################################################
[user attributes]
debug.breakpoints = {loc('aggregate.py'): {198L: (0,
        None,
        1,
        0)}}
debug.exceptions-ignored = {loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/_pytest/_code/code.py'): {213: True},
                            loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/_pytest/config/__init__.py'): {1179: True},
                            loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/_pytest/python.py'): {515: True},
                            loc('../../../miniconda3/envs/crowns/lib/python3.7/site-packages/_pytest/config/__init__.py'): {1130: True}}
guimgr.overall-gui-state = {'windowing-policy': 'combined-window',
                            'windows': [{'name': 'cNyyWhTuba9As824nEqL4DMa8p'\
        'ddQX4l',
        'size-state': '',
        'type': 'dock',
        'view': {'area': 'tall',
                 'constraint': None,
                 'current_pages': [0,
                                   0],
                 'full-screen': False,
                 'notebook_display': 'normal',
                 'notebook_percent': 0.25,
                 'override_title': None,
                 'pagelist': [('project',
                               'tall',
                               0,
                               {'tree-state': {'file-sort-method': 'by name',
        'list-files-first': False,
        'tree-states': {'deep': {'expanded-nodes': [],
                                 'selected-nodes': [],
                                 'top-node': ()}},
        'tree-style': 'deep'}}),
                              ('browser',
                               'tall',
                               0,
                               {}),
                              ('snippets',
                               'tall',
                               0,
                               {}),
                              ('source-assistant',
                               'tall',
                               2,
                               {}),
                              ('debug-stack',
                               'tall',
                               1,
                               {}),
                              ('indent',
                               'tall',
                               2,
                               {})],
                 'primary_view_state': {'area': 'wide',
        'constraint': None,
        'current_pages': [0,
                          4],
        'notebook_display': 'normal',
        'notebook_percent': 0.30000000000000004,
        'override_title': None,
        'pagelist': [('batch-search',
                      'wide',
                      0,
                      {'fScope': {'fFileSetName': 'All Source Files',
                                  'fLocation': None,
                                  'fRecursive': True,
                                  'fType': 'project-files'},
                       'fSearchSpec': {'fEndPos': None,
                                       'fIncludeLinenos': True,
                                       'fInterpretBackslashes': False,
                                       'fMatchCase': False,
                                       'fOmitBinary': True,
                                       'fRegexFlags': 46,
                                       'fReplaceText': '',
                                       'fReverse': False,
                                       'fSearchText': u'version',
                                       'fStartPos': 0,
                                       'fStyle': 'text',
                                       'fWholeWords': False,
                                       'fWrap': True},
                       'fUIOptions': {'fAutoBackground': True,
                                      'fFilePrefix': 'short-file',
                                      'fFindAfterReplace': True,
                                      'fInSelection': False,
                                      'fIncremental': True,
                                      'fReplaceOnDisk': False,
                                      'fShowFirstMatch': False,
                                      'fShowLineno': True,
                                      'fShowReplaceWidgets': False},
                       'replace-entry-expanded': False,
                       'search-entry-expanded': False}),
                     ('interactive-search',
                      'wide',
                      0,
                      {}),
                     ('debug-data',
                      'wide',
                      0,
                      {}),
                     ('debug-exceptions',
                      'wide',
                      0,
                      {}),
                     ('debug-breakpoints',
                      'wide',
                      0,
                      {}),
                     ('testing',
                      'wide',
                      0,
                      {}),
                     ('debug-io',
                      'wide',
                      1,
                      {}),
                     ('debug-probe',
                      'wide',
                      2,
                      {}),
                     ('debug-watch',
                      'wide',
                      1,
                      {}),
                     ('debug-modules',
                      'wide',
                      1,
                      {}),
                     ('python-shell',
                      'wide',
                      2,
                      {'active-range': (None,
        -1,
        -1),
                       'attrib-starts': [],
                       'first-line': 149L,
                       'folded-linenos': [],
                       'history': {None: ['from matplotlib import pyplot\nfr'\
        'om PIL import Image\n\nimg.Image.open("/Users/ben/Dropbox/Weecology'\
        '/competition/IDTREES_competition_train/RemoteSensing/RGB/MLBS_12.ti'\
        'f")\nplt.imshow(img)\n\n',
        'from matplotlib import pyplot\nfrom PIL import Image\n\nimg = Image'\
        '.open("/Users/ben/Dropbox/Weecology/competition/IDTREES_competition'\
        '_train/RemoteSensing/RGB/MLBS_12.tif")\nplt.imshow(img)\n\n',
        'img = cv2.imread("/Users/ben/Dropbox/Weecology/competition/IDTREES_'\
        'competition_train/RemoteSensing/RGB/MLBS_12.tif")\nplt.imshow(img)'\
        '\n\n',
        'from matplotlib import pyplot\nimport cv2\n\nimg = cv2.imread("/Use'\
        'rs/ben/Dropbox/Weecology/competition/IDTREES_competition_train/Remo'\
        'teSensing/RGB/MLBS_12.tif")\nplt.imshow(img)\n\n',
        'from matplotlib import pyplot\nimport cv2\n\nimg = cv2.imread("/Use'\
        'rs/ben/Dropbox/Weecology/competition/IDTREES_competition_train/Remo'\
        'teSensing/RGB/MLBS_12.tif")\npyplot.imshow(img)\n\n',
        'img = cv2.imread("/Users/ben/Dropbox/Weecology/competition/IDTREES_'\
        'competition_train/RemoteSensing/RGB/MLBS_12.tif")\n',
        'img\n',
        'img = rasterio.open("/Users/ben/Dropbox/Weecology/competition/IDTRE'\
        'ES_competition_train/RemoteSensing/RGB/MLBS_12.tif")\n',
        'from matplotlib import pyplot\nimport rasterio\n\nimg = rasterio.op'\
        'en("/Users/ben/Dropbox/Weecology/competition/IDTREES_competition_tr'\
        'ain/RemoteSensing/RGB/MLBS_12.tif")\nsrc=img.read()\npyplot.imshow('\
        'src)\n\n',
        'src\n',
        'img.plot()\n',
        'src.plot()\n',
        'np.rollaxis(img,0,3)\n',
        'img = rasterio.open("/Users/ben/Dropbox/Weecology/competition/IDTRE'\
        'ES_competition_train/RemoteSensing/RGB/MLBS_12.tif")\nsrc=img.read('\
        ')\nsrc=np.rollaxis(src,0,3)\n\n',
        'from matplotlib import pyplot\nimport rasterio\nimport numpy as np'\
        '\n\nimg = rasterio.open("/Users/ben/Dropbox/Weecology/competition/I'\
        'DTREES_competition_train/RemoteSensing/RGB/MLBS_12.tif")\nsrc=img.r'\
        'ead()\nsrc=np.rollaxis(src,0,3)\n\n#Channels last\npyplot.imshow(sr'\
        'c)\n\n']},
                       'launch-id': None,
                       'sel-line': 157L,
                       'sel-line-start': 7227L,
                       'selection_end': 7227L,
                       'selection_start': 7227L,
                       'zoom': 0L}),
                     ('bookmarks',
                      'wide',
                      1,
                      {}),
                     ('messages',
                      'wide',
                      2,
                      {}),
                     ('os-command',
                      'wide',
                      1,
                      {})],
        'primary_view_state': {'editor_states': ({'bookmarks': ([[loc('unknown:untitled-4.py'),
        {'attrib-starts': [],
         'first-line': 0L,
         'folded-linenos': [],
         'sel-line': 0L,
         'sel-line-start': 0L,
         'selection_end': 186L,
         'selection_start': 0L,
         'zoom': 0L},
        1588267099.615213],
        [loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/PIL/Image.py'),
         {'attrib-starts': [('open',
                             2803)],
          'first-line': 2780L,
          'folded-linenos': [],
          'sel-line': 2803L,
          'sel-line-start': 94622L,
          'selection_end': 94622L,
          'selection_start': 94622L,
          'zoom': 0L},
         1588267106.132308],
        [loc('unknown:untitled-4.py'),
         {'attrib-starts': [],
          'first-line': 0L,
          'folded-linenos': [],
          'sel-line': 0L,
          'sel-line-start': 0L,
          'selection_end': 178L,
          'selection_start': 0L,
          'zoom': 0L},
         1588267135.760149],
        [loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/matplotlib/image.py'),
         {'attrib-starts': [('_ImageBase',
                             219),
                            ('_ImageBase.write_png',
                             663)],
          'first-line': 648L,
          'folded-linenos': [],
          'sel-line': 668L,
          'sel-line-start': 25992L,
          'selection_end': 26022L,
          'selection_start': 26022L,
          'zoom': 0L},
         1588267145.462595],
        [loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/PIL/Image.py'),
         {'attrib-starts': [('open',
                             2803)],
          'first-line': 2780L,
          'folded-linenos': [],
          'sel-line': 2803L,
          'sel-line-start': 94622L,
          'selection_end': 94622L,
          'selection_start': 94622L,
          'zoom': 0L},
         1588267147.158993],
        [loc('unknown:untitled-4.py'),
         {'attrib-starts': [],
          'first-line': 0L,
          'folded-linenos': [],
          'sel-line': 0L,
          'sel-line-start': 0L,
          'selection_end': 200L,
          'selection_start': 0L,
          'zoom': 0L},
         1588267202.495262],
        [loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/matplotlib/image.py'),
         {'attrib-starts': [('_ImageBase',
                             219),
                            ('_ImageBase.set_data',
                             671)],
          'first-line': 658L,
          'folded-linenos': [],
          'sel-line': 671L,
          'sel-line-start': 26084L,
          'selection_end': 26084L,
          'selection_start': 26084L,
          'zoom': 0L},
         1588267208.700073]],
        7),
        'current-loc': None,
        'editor-state-list': [(loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/matplotlib/image.py'),
                               {'attrib-starts': [('_ImageBase',
        219),
        ('_ImageBase.set_data',
         671)],
                                'first-line': 658L,
                                'folded-linenos': [],
                                'sel-line': 671L,
                                'sel-line-start': 26084L,
                                'selection_end': 26084L,
                                'selection_start': 26084L,
                                'zoom': 0L})],
        'has-focus': True,
        'locked': False},
        [loc('unknown:untitled-4.py'),
         loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/matplotlib/image.py')]),
                               'open_files': ['unknown:untitled-4.py']},
        'saved_notebook_display': None,
        'split_percents': {0: 0.5},
        'splits': 2,
        'tab_location': 'top',
        'user_data': {}},
                 'saved_notebook_display': None,
                 'split_percents': {0: 0.5},
                 'splits': 2,
                 'tab_location': 'left',
                 'user_data': {}},
        'window-alloc': (0,
                         23,
                         1418,
                         877)}]}
guimgr.recent-documents = [loc('unknown:untitled-4.py'),
                           loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/matplotlib/image.py')]
guimgr.visual-state = {loc('../../DeepForest_Model/GenerateAnchors.py'): {'a'\
        'ttrib-starts': [],
        'first-line': 0L,
        'folded-linenos': [],
        'sel-line': 12L,
        'sel-line-start': 299L,
        'selection_end': 318L,
        'selection_start': 318L,
        'zoom': 0L},
                       loc('../../DeepForest_Model/generate.py'): {'attrib-s'\
        'tarts': [],
        'first-line': 225L,
        'folded-linenos': [],
        'sel-line': 0L,
        'sel-line-start': 0L,
        'selection_end': 0L,
        'selection_start': 0L,
        'zoom': 0L},
                       loc('cron.txt'): {'attrib-starts': [],
        'first-line': 0L,
        'folded-linenos': [],
        'sel-line': 5L,
        'sel-line-start': 281L,
        'selection_end': 304L,
        'selection_start': 304L,
        'zoom': 0L},
                       loc('extract_old.py'): {'attrib-starts': [],
        'first-line': 0L,
        'folded-linenos': [],
        'sel-line': 17L,
        'sel-line-start': 528L,
        'selection_end': 532L,
        'selection_start': 532L,
        'zoom': 0L},
                       loc('tests/test_aggregate.py'): {'attrib-starts': [],
        'first-line': 0L,
        'folded-linenos': [],
        'sel-line': 3L,
        'sel-line-start': 53L,
        'selection_end': 66L,
        'selection_start': 66L,
        'zoom': 0L},
                       loc('tests/test_tile_raster.py'): {'attrib-starts': [],
        'first-line': 0L,
        'folded-linenos': [],
        'sel-line': 0L,
        'sel-line-start': 0L,
        'selection_end': 0L,
        'selection_start': 0L,
        'zoom': 0L},
                       loc('tile_raster.py'): {'attrib-starts': [('parse_arg'\
        's',
        8)],
        'first-line': 0L,
        'folded-linenos': [],
        'sel-line': 10L,
        'sel-line-start': 233L,
        'selection_end': 296L,
        'selection_start': 296L,
        'zoom': 0L},
                       loc('upload.sh'): {'attrib-starts': [],
        'first-line': 0L,
        'folded-linenos': [],
        'sel-line': 1L,
        'sel-line-start': 31L,
        'selection_end': 157L,
        'selection_start': 31L,
        'zoom': 0L},
                       loc('../../NEON_crown_maps/hard_mining.py'): {'attrib'\
        '-starts': [],
        'first-line': 98L,
        'folded-linenos': [],
        'sel-line': 128L,
        'sel-line-start': 4764L,
        'selection_end': 4764L,
        'selection_start': 4764L,
        'zoom': 0L},
                       loc('../../NEON_crown_maps/main.py'): {'attrib-starts': [('g'\
        'enerate_tfrecord',
        69)],
        'first-line': 22L,
        'folded-linenos': [],
        'sel-line': 112L,
        'sel-line-start': 3934L,
        'selection_end': 3938L,
        'selection_start': 3938L,
        'zoom': 0L},
                       loc('../../NEON_crown_maps/predict.py'): {'attrib-sta'\
        'rts': [],
        'first-line': 102L,
        'folded-linenos': [],
        'sel-line': 0L,
        'sel-line-start': 0L,
        'selection_end': 0L,
        'selection_start': 0L,
        'zoom': 0L},
                       loc('../../NEON_crown_maps/tests/test_sampling.py'): {'a'\
        'ttrib-starts': [],
        'first-line': 0L,
        'folded-linenos': [],
        'sel-line': 2L,
        'sel-line-start': 25L,
        'selection_end': 132L,
        'selection_start': 25L,
        'zoom': 0L},
                       loc('../../../miniconda3/envs/Zooniverse/lib/python3.6/site-packages/_pytest/python.py'): {'a'\
        'ttrib-starts': [],
        'first-line': 0L,
        'folded-linenos': [],
        'sel-line': 0L,
        'sel-line-start': 0L,
        'selection_end': 0L,
        'selection_start': 0L,
        'zoom': 0L},
                       loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/_pytest/python.py'): {'a'\
        'ttrib-starts': [('Module',
                          440),
                         ('Module._importtestmodule',
                          508)],
        'first-line': 509L,
        'folded-linenos': [],
        'sel-line': 514L,
        'sel-line-start': 18945L,
        'selection_end': 18945L,
        'selection_start': 18945L,
        'zoom': 0L},
                       loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/generic.py'): {'a'\
        'ttrib-starts': [('NDFrame',
                          150),
                         ('NDFrame.__getattr__',
                          5256)],
        'first-line': 5258L,
        'folded-linenos': [],
        'sel-line': 5273L,
        'sel-line-start': 176248L,
        'selection_end': 176248L,
        'selection_start': 176248L,
        'zoom': 0L},
                       loc('../../../miniconda3/envs/Zooniverse/lib/python3.7/site-packages/requests/adapters.py'): {'a'\
        'ttrib-starts': [('HTTPAdapter',
                          83),
                         ('HTTPAdapter.send',
                          393)],
        'first-line': 478L,
        'folded-linenos': [],
        'sel-line': 499L,
        'sel-line-start': 20078L,
        'selection_end': 20112L,
        'selection_start': 20112L,
        'zoom': 0L}}
proj.build-cmd = {None: ('default',
                         None)}
proj.env-vars = {None: ('default',
                        [u''])}
proj.pyexec = {None: ('custom',
                      u'/Users/ben/miniconda3/envs/Zooniverse/bin/python')}
proj.vcs-system-config = ('prefs',
                          {'bzr': {'versioncontrol.bzr.active': 'active-if-p'\
        'roject-dir',
                                   'versioncontrol.bzr.executable': u'bzr'},
                           'cvs': {'versioncontrol.cvs.active': 'active-if-p'\
        'roject-dir',
                                   'versioncontrol.cvs.executable': u'cvs',
                                   'versioncontrol.cvs.extra-global-args': '-'\
        'z3'},
                           'git': {'versioncontrol.git.active': 'active-if-p'\
        'roject-dir',
                                   'versioncontrol.git.executable': u'git',
                                   'versioncontrol.git.use-porcelain': True},
                           'hg': {'versioncontrol.hg.active': 'active-if-pro'\
        'ject-dir',
                                  'versioncontrol.hg.dont-find-unregistered': True,
                                  'versioncontrol.hg.executable': u'hg',
                                  'versioncontrol.hg.extra-global-args': '--'\
        'encoding=utf8'},
                           'perforce': {'versioncontrol.perforce.active': 'n'\
        'ot-active',
        'versioncontrol.perforce.dont-find-unregistered': True,
        'versioncontrol.perforce.executable': u'p4',
        'versioncontrol.perforce.extra-global-args': ''},
                           'svn': {'versioncontrol.svn.active': 'active-if-p'\
        'roject-dir',
                                   'versioncontrol.svn.executable': u'svn',
                                   'versioncontrol.svn.extra-global-args': '',
                                   'versioncontrol.svn.svnadmin-executable': u'svnadmin'}})
search.search-history = [u'version',
                         u'min_version',
                         u'min',
                         u'load_classification',
                         u'select',
                         u'crs',
                         u'epsg',
                         u'to_file',
                         u'parse_subject_data',
                         u'download',
                         u'png',
                         u'project',
                         u'site',
                         u'parse_ann',
                         u'Project',
                         u'connect',
                         u'auth',
                         u'projecg',
                         u'box',
                         u'bounds']
testing.run-as-package-module = {None: False}
testing.stored-results = (1,
                          [(u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/tests/test_aggregate.py',
                            [('test_run[False]',
                              1,
                              None,
                              None,
                              ('',
                               "<ExceptionInfo ValueError('No objects to con"\
                               "catenate') tblen=5>",
                               'ValueError: No objects to concatenate',
                               [(u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/tests/test_aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/tests/test_aggregate.py',
                                 53,
                                 'test_run',
                                 None,
                                 '    aggregate.run("data/old_workflow.csv",'\
                                 'min_version, download=download, savedir="o'\
                                 'utput")'),
                                (u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/aggregate.py',
                                 190,
                                 'run',
                                 None,
                                 '    df = parse_file(df, version)'),
                                (u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/aggregate.py',
                                 106,
                                 'parse_file',
                                 None,
                                 '    results = pd.concat(results)'),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/reshape/concat.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/reshap'\
                                 'e/concat.py',
                                 280,
                                 'concat',
                                 None,
                                 '    op = _Concatenator('),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/reshape/concat.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/reshap'\
                                 'e/concat.py',
                                 328,
                                 '__init__',
                                 None,
                                 '            raise ValueError("No objects t'\
                                 'o concatenate")')],
                               0,
                               None,
                               None,
                               None,
                               None),
                              1588198337,
                              51),
                             ('test_parse_file',
                              1,
                              None,
                              None,
                              ('',
                               "<ExceptionInfo ValueError('No objects to con"\
                               "catenate') tblen=4>",
                               'ValueError: No objects to concatenate',
                               [(u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/tests/test_aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/tests/test_aggregate.py',
                                 34,
                                 'test_parse_file',
                                 None,
                                 '    df = aggregate.parse_file(csv_data,min'\
                                 '_version)'),
                                (u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/aggregate.py',
                                 106,
                                 'parse_file',
                                 None,
                                 '    results = pd.concat(results)'),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/reshape/concat.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/reshap'\
                                 'e/concat.py',
                                 280,
                                 'concat',
                                 None,
                                 '    op = _Concatenator('),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/reshape/concat.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/reshap'\
                                 'e/concat.py',
                                 328,
                                 '__init__',
                                 None,
                                 '            raise ValueError("No objects t'\
                                 'o concatenate")')],
                               0,
                               None,
                               None,
                               None,
                               None),
                              1588198337,
                              33),
                             ('test_spatial_join',
                              1,
                              None,
                              None,
                              ('',
                               "<ExceptionInfo ValueError('No objects to con"\
                               "catenate') tblen=4>",
                               'ValueError: No objects to concatenate',
                               [(u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/tests/test_aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/tests/test_aggregate.py',
                                 46,
                                 'test_spatial_join',
                                 None,
                                 '    df = aggregate.parse_file(csv_data,min'\
                                 '_version)'),
                                (u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/aggregate.py',
                                 106,
                                 'parse_file',
                                 None,
                                 '    results = pd.concat(results)'),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/reshape/concat.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/reshap'\
                                 'e/concat.py',
                                 280,
                                 'concat',
                                 None,
                                 '    op = _Concatenator('),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/reshape/concat.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/reshap'\
                                 'e/concat.py',
                                 328,
                                 '__init__',
                                 None,
                                 '            raise ValueError("No objects t'\
                                 'o concatenate")')],
                               0,
                               None,
                               None,
                               None,
                               None),
                              1588198337,
                              45),
                             ('test_project',
                              1,
                              None,
                              None,
                              ('',
                               "<ExceptionInfo ValueError('No objects to con"\
                               "catenate') tblen=4>",
                               'ValueError: No objects to concatenate',
                               [(u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/tests/test_aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/tests/test_aggregate.py',
                                 39,
                                 'test_project',
                                 None,
                                 '    df = aggregate.parse_file(df, min_vers'\
                                 'ion)'),
                                (u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/aggregate.py',
                                 106,
                                 'parse_file',
                                 None,
                                 '    results = pd.concat(results)'),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/reshape/concat.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/reshap'\
                                 'e/concat.py',
                                 280,
                                 'concat',
                                 None,
                                 '    op = _Concatenator('),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/reshape/concat.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/reshap'\
                                 'e/concat.py',
                                 328,
                                 '__init__',
                                 None,
                                 '            raise ValueError("No objects t'\
                                 'o concatenate")')],
                               0,
                               None,
                               None,
                               None,
                               None),
                              1588198337,
                              37),
                             ('test_parse_annotations',
                              1,
                              None,
                              None,
                              ('',
                               "<ExceptionInfo IndexError('single positional"\
                               " indexer is out-of-bounds') tblen=4>",
                               'IndexError: single positional indexer is out'\
                               '-of-bounds',
                               [(u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/tests/test_aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/tests/test_aggregate.py',
                                 25,
                                 'test_parse_annotations',
                                 None,
                                 '    annotations = aggregate.parse_annotati'\
                                 'ons(csv_data.annotations.iloc[0])'),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/indexing.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/indexi'\
                                 'ng.py',
                                 1767,
                                 '__getitem__',
                                 None,
                                 '            return self._getitem_axis(mayb'\
                                 'e_callable, axis=axis)'),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/indexing.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/indexi'\
                                 'ng.py',
                                 2137,
                                 '_getitem_axis',
                                 None,
                                 '            self._validate_integer(key, ax'\
                                 'is)'),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/indexing.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/indexi'\
                                 'ng.py',
                                 2062,
                                 '_validate_integer',
                                 None,
                                 '            raise IndexError("single posit'\
                                 'ional indexer is out-of-bounds")')],
                               0,
                               None,
                               None,
                               None,
                               None),
                              1588198337,
                              24),
                             ('test_load_classifications',
                              0,
                              None,
                              None,
                              None,
                              1588198337,
                              20),
                             ('test_download_data[False]',
                              0,
                              None,
                              None,
                              None,
                              1588198337,
                              56),
                             ('test_parse_subject_data',
                              1,
                              None,
                              None,
                              ('',
                               "<ExceptionInfo IndexError('single positional"\
                               " indexer is out-of-bounds') tblen=4>",
                               'IndexError: single positional indexer is out'\
                               '-of-bounds',
                               [(u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/tests/test_aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/tests/test_aggregate.py',
                                 29,
                                 'test_parse_subject_data',
                                 None,
                                 '    subject_data = aggregate.parse_subject'\
                                 '_data(csv_data.subject_data.iloc[40])'),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/indexing.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/indexi'\
                                 'ng.py',
                                 1767,
                                 '__getitem__',
                                 None,
                                 '            return self._getitem_axis(mayb'\
                                 'e_callable, axis=axis)'),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/indexing.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/indexi'\
                                 'ng.py',
                                 2137,
                                 '_getitem_axis',
                                 None,
                                 '            self._validate_integer(key, ax'\
                                 'is)'),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/indexing.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/indexi'\
                                 'ng.py',
                                 2062,
                                 '_validate_integer',
                                 None,
                                 '            raise IndexError("single posit'\
                                 'ional indexer is out-of-bounds")')],
                               0,
                               None,
                               None,
                               None,
                               None),
                              1588198337,
                              28),
                             ('test_run[True]',
                              1,
                              None,
                              None,
                              ('',
                               "<ExceptionInfo ValueError('No objects to con"\
                               "catenate') tblen=5>",
                               'ValueError: No objects to concatenate',
                               [(u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/tests/test_aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/tests/test_aggregate.py',
                                 53,
                                 'test_run',
                                 None,
                                 '    aggregate.run("data/old_workflow.csv",'\
                                 'min_version, download=download, savedir="o'\
                                 'utput")'),
                                (u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/aggregate.py',
                                 190,
                                 'run',
                                 None,
                                 '    df = parse_file(df, version)'),
                                (u'/Users/ben/Documents/EvergladesWadingBird/Zooniverse/aggregate.py',
                                 '/Users/ben/Documents/EvergladesWadingBird/'\
                                 'Zooniverse/aggregate.py',
                                 106,
                                 'parse_file',
                                 None,
                                 '    results = pd.concat(results)'),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/reshape/concat.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/reshap'\
                                 'e/concat.py',
                                 280,
                                 'concat',
                                 None,
                                 '    op = _Concatenator('),
                                (u'/Users/ben/miniconda3/envs/Zooniverse/lib/python3.7/site-packages/pandas/core/reshape/concat.py',
                                 '/Users/ben/miniconda3/envs/Zooniverse/lib/'\
                                 'python3.7/site-packages/pandas/core/reshap'\
                                 'e/concat.py',
                                 328,
                                 '__init__',
                                 None,
                                 '            raise ValueError("No objects t'\
                                 'o concatenate")')],
                               0,
                               None,
                               None,
                               None,
                               None),
                              1588198337,
                              51)])],
                          {})
